// Code generated by mockery v2.53.4. DO NOT EDIT.

package mocks

import (
	context "context"

	model "github.com/andrewsvn/gophermart-ls/internal/model"
	mock "github.com/stretchr/testify/mock"

	time "time"

	uuid "github.com/google/uuid"
)

// MockLoyaltyStorage is an autogenerated mock type for the LoyaltyStorage type
type MockLoyaltyStorage struct {
	mock.Mock
}

type MockLoyaltyStorage_Expecter struct {
	mock *mock.Mock
}

func (_m *MockLoyaltyStorage) EXPECT() *MockLoyaltyStorage_Expecter {
	return &MockLoyaltyStorage_Expecter{mock: &_m.Mock}
}

// CreateNewOrder provides a mock function with given fields: ctx, orderID, userID
func (_m *MockLoyaltyStorage) CreateNewOrder(ctx context.Context, orderID string, userID uuid.UUID) error {
	ret := _m.Called(ctx, orderID, userID)

	if len(ret) == 0 {
		panic("no return value specified for CreateNewOrder")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, string, uuid.UUID) error); ok {
		r0 = rf(ctx, orderID, userID)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// MockLoyaltyStorage_CreateNewOrder_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'CreateNewOrder'
type MockLoyaltyStorage_CreateNewOrder_Call struct {
	*mock.Call
}

// CreateNewOrder is a helper method to define mock.On call
//   - ctx context.Context
//   - orderID string
//   - userID uuid.UUID
func (_e *MockLoyaltyStorage_Expecter) CreateNewOrder(ctx interface{}, orderID interface{}, userID interface{}) *MockLoyaltyStorage_CreateNewOrder_Call {
	return &MockLoyaltyStorage_CreateNewOrder_Call{Call: _e.mock.On("CreateNewOrder", ctx, orderID, userID)}
}

func (_c *MockLoyaltyStorage_CreateNewOrder_Call) Run(run func(ctx context.Context, orderID string, userID uuid.UUID)) *MockLoyaltyStorage_CreateNewOrder_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string), args[2].(uuid.UUID))
	})
	return _c
}

func (_c *MockLoyaltyStorage_CreateNewOrder_Call) Return(_a0 error) *MockLoyaltyStorage_CreateNewOrder_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockLoyaltyStorage_CreateNewOrder_Call) RunAndReturn(run func(context.Context, string, uuid.UUID) error) *MockLoyaltyStorage_CreateNewOrder_Call {
	_c.Call.Return(run)
	return _c
}

// FetchOrderIDsForUpdate provides a mock function with given fields: ctx, limit
func (_m *MockLoyaltyStorage) FetchOrderIDsForUpdate(ctx context.Context, limit uint64) ([]string, error) {
	ret := _m.Called(ctx, limit)

	if len(ret) == 0 {
		panic("no return value specified for FetchOrderIDsForUpdate")
	}

	var r0 []string
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, uint64) ([]string, error)); ok {
		return rf(ctx, limit)
	}
	if rf, ok := ret.Get(0).(func(context.Context, uint64) []string); ok {
		r0 = rf(ctx, limit)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]string)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, uint64) error); ok {
		r1 = rf(ctx, limit)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockLoyaltyStorage_FetchOrderIDsForUpdate_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'FetchOrderIDsForUpdate'
type MockLoyaltyStorage_FetchOrderIDsForUpdate_Call struct {
	*mock.Call
}

// FetchOrderIDsForUpdate is a helper method to define mock.On call
//   - ctx context.Context
//   - limit uint64
func (_e *MockLoyaltyStorage_Expecter) FetchOrderIDsForUpdate(ctx interface{}, limit interface{}) *MockLoyaltyStorage_FetchOrderIDsForUpdate_Call {
	return &MockLoyaltyStorage_FetchOrderIDsForUpdate_Call{Call: _e.mock.On("FetchOrderIDsForUpdate", ctx, limit)}
}

func (_c *MockLoyaltyStorage_FetchOrderIDsForUpdate_Call) Run(run func(ctx context.Context, limit uint64)) *MockLoyaltyStorage_FetchOrderIDsForUpdate_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(uint64))
	})
	return _c
}

func (_c *MockLoyaltyStorage_FetchOrderIDsForUpdate_Call) Return(_a0 []string, _a1 error) *MockLoyaltyStorage_FetchOrderIDsForUpdate_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockLoyaltyStorage_FetchOrderIDsForUpdate_Call) RunAndReturn(run func(context.Context, uint64) ([]string, error)) *MockLoyaltyStorage_FetchOrderIDsForUpdate_Call {
	_c.Call.Return(run)
	return _c
}

// GetOrderByID provides a mock function with given fields: ctx, orderID
func (_m *MockLoyaltyStorage) GetOrderByID(ctx context.Context, orderID string) (*model.Order, error) {
	ret := _m.Called(ctx, orderID)

	if len(ret) == 0 {
		panic("no return value specified for GetOrderByID")
	}

	var r0 *model.Order
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string) (*model.Order, error)); ok {
		return rf(ctx, orderID)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string) *model.Order); ok {
		r0 = rf(ctx, orderID)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*model.Order)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, string) error); ok {
		r1 = rf(ctx, orderID)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockLoyaltyStorage_GetOrderByID_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetOrderByID'
type MockLoyaltyStorage_GetOrderByID_Call struct {
	*mock.Call
}

// GetOrderByID is a helper method to define mock.On call
//   - ctx context.Context
//   - orderID string
func (_e *MockLoyaltyStorage_Expecter) GetOrderByID(ctx interface{}, orderID interface{}) *MockLoyaltyStorage_GetOrderByID_Call {
	return &MockLoyaltyStorage_GetOrderByID_Call{Call: _e.mock.On("GetOrderByID", ctx, orderID)}
}

func (_c *MockLoyaltyStorage_GetOrderByID_Call) Run(run func(ctx context.Context, orderID string)) *MockLoyaltyStorage_GetOrderByID_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string))
	})
	return _c
}

func (_c *MockLoyaltyStorage_GetOrderByID_Call) Return(_a0 *model.Order, _a1 error) *MockLoyaltyStorage_GetOrderByID_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockLoyaltyStorage_GetOrderByID_Call) RunAndReturn(run func(context.Context, string) (*model.Order, error)) *MockLoyaltyStorage_GetOrderByID_Call {
	_c.Call.Return(run)
	return _c
}

// GetOrdersByUserID provides a mock function with given fields: ctx, userID
func (_m *MockLoyaltyStorage) GetOrdersByUserID(ctx context.Context, userID uuid.UUID) ([]*model.Order, error) {
	ret := _m.Called(ctx, userID)

	if len(ret) == 0 {
		panic("no return value specified for GetOrdersByUserID")
	}

	var r0 []*model.Order
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, uuid.UUID) ([]*model.Order, error)); ok {
		return rf(ctx, userID)
	}
	if rf, ok := ret.Get(0).(func(context.Context, uuid.UUID) []*model.Order); ok {
		r0 = rf(ctx, userID)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]*model.Order)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, uuid.UUID) error); ok {
		r1 = rf(ctx, userID)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockLoyaltyStorage_GetOrdersByUserID_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetOrdersByUserID'
type MockLoyaltyStorage_GetOrdersByUserID_Call struct {
	*mock.Call
}

// GetOrdersByUserID is a helper method to define mock.On call
//   - ctx context.Context
//   - userID uuid.UUID
func (_e *MockLoyaltyStorage_Expecter) GetOrdersByUserID(ctx interface{}, userID interface{}) *MockLoyaltyStorage_GetOrdersByUserID_Call {
	return &MockLoyaltyStorage_GetOrdersByUserID_Call{Call: _e.mock.On("GetOrdersByUserID", ctx, userID)}
}

func (_c *MockLoyaltyStorage_GetOrdersByUserID_Call) Run(run func(ctx context.Context, userID uuid.UUID)) *MockLoyaltyStorage_GetOrdersByUserID_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(uuid.UUID))
	})
	return _c
}

func (_c *MockLoyaltyStorage_GetOrdersByUserID_Call) Return(_a0 []*model.Order, _a1 error) *MockLoyaltyStorage_GetOrdersByUserID_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockLoyaltyStorage_GetOrdersByUserID_Call) RunAndReturn(run func(context.Context, uuid.UUID) ([]*model.Order, error)) *MockLoyaltyStorage_GetOrdersByUserID_Call {
	_c.Call.Return(run)
	return _c
}

// GetUserBalance provides a mock function with given fields: ctx, userID
func (_m *MockLoyaltyStorage) GetUserBalance(ctx context.Context, userID uuid.UUID) (*model.Balance, error) {
	ret := _m.Called(ctx, userID)

	if len(ret) == 0 {
		panic("no return value specified for GetUserBalance")
	}

	var r0 *model.Balance
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, uuid.UUID) (*model.Balance, error)); ok {
		return rf(ctx, userID)
	}
	if rf, ok := ret.Get(0).(func(context.Context, uuid.UUID) *model.Balance); ok {
		r0 = rf(ctx, userID)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*model.Balance)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, uuid.UUID) error); ok {
		r1 = rf(ctx, userID)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockLoyaltyStorage_GetUserBalance_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetUserBalance'
type MockLoyaltyStorage_GetUserBalance_Call struct {
	*mock.Call
}

// GetUserBalance is a helper method to define mock.On call
//   - ctx context.Context
//   - userID uuid.UUID
func (_e *MockLoyaltyStorage_Expecter) GetUserBalance(ctx interface{}, userID interface{}) *MockLoyaltyStorage_GetUserBalance_Call {
	return &MockLoyaltyStorage_GetUserBalance_Call{Call: _e.mock.On("GetUserBalance", ctx, userID)}
}

func (_c *MockLoyaltyStorage_GetUserBalance_Call) Run(run func(ctx context.Context, userID uuid.UUID)) *MockLoyaltyStorage_GetUserBalance_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(uuid.UUID))
	})
	return _c
}

func (_c *MockLoyaltyStorage_GetUserBalance_Call) Return(_a0 *model.Balance, _a1 error) *MockLoyaltyStorage_GetUserBalance_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockLoyaltyStorage_GetUserBalance_Call) RunAndReturn(run func(context.Context, uuid.UUID) (*model.Balance, error)) *MockLoyaltyStorage_GetUserBalance_Call {
	_c.Call.Return(run)
	return _c
}

// GetWithdrawalByID provides a mock function with given fields: ctx, wdID
func (_m *MockLoyaltyStorage) GetWithdrawalByID(ctx context.Context, wdID string) (*model.Withdrawal, error) {
	ret := _m.Called(ctx, wdID)

	if len(ret) == 0 {
		panic("no return value specified for GetWithdrawalByID")
	}

	var r0 *model.Withdrawal
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string) (*model.Withdrawal, error)); ok {
		return rf(ctx, wdID)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string) *model.Withdrawal); ok {
		r0 = rf(ctx, wdID)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*model.Withdrawal)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, string) error); ok {
		r1 = rf(ctx, wdID)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockLoyaltyStorage_GetWithdrawalByID_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetWithdrawalByID'
type MockLoyaltyStorage_GetWithdrawalByID_Call struct {
	*mock.Call
}

// GetWithdrawalByID is a helper method to define mock.On call
//   - ctx context.Context
//   - wdID string
func (_e *MockLoyaltyStorage_Expecter) GetWithdrawalByID(ctx interface{}, wdID interface{}) *MockLoyaltyStorage_GetWithdrawalByID_Call {
	return &MockLoyaltyStorage_GetWithdrawalByID_Call{Call: _e.mock.On("GetWithdrawalByID", ctx, wdID)}
}

func (_c *MockLoyaltyStorage_GetWithdrawalByID_Call) Run(run func(ctx context.Context, wdID string)) *MockLoyaltyStorage_GetWithdrawalByID_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string))
	})
	return _c
}

func (_c *MockLoyaltyStorage_GetWithdrawalByID_Call) Return(_a0 *model.Withdrawal, _a1 error) *MockLoyaltyStorage_GetWithdrawalByID_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockLoyaltyStorage_GetWithdrawalByID_Call) RunAndReturn(run func(context.Context, string) (*model.Withdrawal, error)) *MockLoyaltyStorage_GetWithdrawalByID_Call {
	_c.Call.Return(run)
	return _c
}

// GetWithdrawalsByUserID provides a mock function with given fields: ctx, userID
func (_m *MockLoyaltyStorage) GetWithdrawalsByUserID(ctx context.Context, userID uuid.UUID) ([]*model.Withdrawal, error) {
	ret := _m.Called(ctx, userID)

	if len(ret) == 0 {
		panic("no return value specified for GetWithdrawalsByUserID")
	}

	var r0 []*model.Withdrawal
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, uuid.UUID) ([]*model.Withdrawal, error)); ok {
		return rf(ctx, userID)
	}
	if rf, ok := ret.Get(0).(func(context.Context, uuid.UUID) []*model.Withdrawal); ok {
		r0 = rf(ctx, userID)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]*model.Withdrawal)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, uuid.UUID) error); ok {
		r1 = rf(ctx, userID)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockLoyaltyStorage_GetWithdrawalsByUserID_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetWithdrawalsByUserID'
type MockLoyaltyStorage_GetWithdrawalsByUserID_Call struct {
	*mock.Call
}

// GetWithdrawalsByUserID is a helper method to define mock.On call
//   - ctx context.Context
//   - userID uuid.UUID
func (_e *MockLoyaltyStorage_Expecter) GetWithdrawalsByUserID(ctx interface{}, userID interface{}) *MockLoyaltyStorage_GetWithdrawalsByUserID_Call {
	return &MockLoyaltyStorage_GetWithdrawalsByUserID_Call{Call: _e.mock.On("GetWithdrawalsByUserID", ctx, userID)}
}

func (_c *MockLoyaltyStorage_GetWithdrawalsByUserID_Call) Run(run func(ctx context.Context, userID uuid.UUID)) *MockLoyaltyStorage_GetWithdrawalsByUserID_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(uuid.UUID))
	})
	return _c
}

func (_c *MockLoyaltyStorage_GetWithdrawalsByUserID_Call) Return(_a0 []*model.Withdrawal, _a1 error) *MockLoyaltyStorage_GetWithdrawalsByUserID_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockLoyaltyStorage_GetWithdrawalsByUserID_Call) RunAndReturn(run func(context.Context, uuid.UUID) ([]*model.Withdrawal, error)) *MockLoyaltyStorage_GetWithdrawalsByUserID_Call {
	_c.Call.Return(run)
	return _c
}

// ResetPendingOrders provides a mock function with given fields: ctx
func (_m *MockLoyaltyStorage) ResetPendingOrders(ctx context.Context) error {
	ret := _m.Called(ctx)

	if len(ret) == 0 {
		panic("no return value specified for ResetPendingOrders")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context) error); ok {
		r0 = rf(ctx)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// MockLoyaltyStorage_ResetPendingOrders_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'ResetPendingOrders'
type MockLoyaltyStorage_ResetPendingOrders_Call struct {
	*mock.Call
}

// ResetPendingOrders is a helper method to define mock.On call
//   - ctx context.Context
func (_e *MockLoyaltyStorage_Expecter) ResetPendingOrders(ctx interface{}) *MockLoyaltyStorage_ResetPendingOrders_Call {
	return &MockLoyaltyStorage_ResetPendingOrders_Call{Call: _e.mock.On("ResetPendingOrders", ctx)}
}

func (_c *MockLoyaltyStorage_ResetPendingOrders_Call) Run(run func(ctx context.Context)) *MockLoyaltyStorage_ResetPendingOrders_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context))
	})
	return _c
}

func (_c *MockLoyaltyStorage_ResetPendingOrders_Call) Return(_a0 error) *MockLoyaltyStorage_ResetPendingOrders_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockLoyaltyStorage_ResetPendingOrders_Call) RunAndReturn(run func(context.Context) error) *MockLoyaltyStorage_ResetPendingOrders_Call {
	_c.Call.Return(run)
	return _c
}

// TryCreateWithdrawal provides a mock function with given fields: ctx, wdID, userID, amount
func (_m *MockLoyaltyStorage) TryCreateWithdrawal(ctx context.Context, wdID string, userID uuid.UUID, amount float64) error {
	ret := _m.Called(ctx, wdID, userID, amount)

	if len(ret) == 0 {
		panic("no return value specified for TryCreateWithdrawal")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, string, uuid.UUID, float64) error); ok {
		r0 = rf(ctx, wdID, userID, amount)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// MockLoyaltyStorage_TryCreateWithdrawal_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'TryCreateWithdrawal'
type MockLoyaltyStorage_TryCreateWithdrawal_Call struct {
	*mock.Call
}

// TryCreateWithdrawal is a helper method to define mock.On call
//   - ctx context.Context
//   - wdID string
//   - userID uuid.UUID
//   - amount float64
func (_e *MockLoyaltyStorage_Expecter) TryCreateWithdrawal(ctx interface{}, wdID interface{}, userID interface{}, amount interface{}) *MockLoyaltyStorage_TryCreateWithdrawal_Call {
	return &MockLoyaltyStorage_TryCreateWithdrawal_Call{Call: _e.mock.On("TryCreateWithdrawal", ctx, wdID, userID, amount)}
}

func (_c *MockLoyaltyStorage_TryCreateWithdrawal_Call) Run(run func(ctx context.Context, wdID string, userID uuid.UUID, amount float64)) *MockLoyaltyStorage_TryCreateWithdrawal_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string), args[2].(uuid.UUID), args[3].(float64))
	})
	return _c
}

func (_c *MockLoyaltyStorage_TryCreateWithdrawal_Call) Return(_a0 error) *MockLoyaltyStorage_TryCreateWithdrawal_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockLoyaltyStorage_TryCreateWithdrawal_Call) RunAndReturn(run func(context.Context, string, uuid.UUID, float64) error) *MockLoyaltyStorage_TryCreateWithdrawal_Call {
	_c.Call.Return(run)
	return _c
}

// UpdateOrderAccrual provides a mock function with given fields: ctx, orderAccrual, timestamp
func (_m *MockLoyaltyStorage) UpdateOrderAccrual(ctx context.Context, orderAccrual *model.OrderAccrual, timestamp time.Time) error {
	ret := _m.Called(ctx, orderAccrual, timestamp)

	if len(ret) == 0 {
		panic("no return value specified for UpdateOrderAccrual")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, *model.OrderAccrual, time.Time) error); ok {
		r0 = rf(ctx, orderAccrual, timestamp)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// MockLoyaltyStorage_UpdateOrderAccrual_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'UpdateOrderAccrual'
type MockLoyaltyStorage_UpdateOrderAccrual_Call struct {
	*mock.Call
}

// UpdateOrderAccrual is a helper method to define mock.On call
//   - ctx context.Context
//   - orderAccrual *model.OrderAccrual
//   - timestamp time.Time
func (_e *MockLoyaltyStorage_Expecter) UpdateOrderAccrual(ctx interface{}, orderAccrual interface{}, timestamp interface{}) *MockLoyaltyStorage_UpdateOrderAccrual_Call {
	return &MockLoyaltyStorage_UpdateOrderAccrual_Call{Call: _e.mock.On("UpdateOrderAccrual", ctx, orderAccrual, timestamp)}
}

func (_c *MockLoyaltyStorage_UpdateOrderAccrual_Call) Run(run func(ctx context.Context, orderAccrual *model.OrderAccrual, timestamp time.Time)) *MockLoyaltyStorage_UpdateOrderAccrual_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(*model.OrderAccrual), args[2].(time.Time))
	})
	return _c
}

func (_c *MockLoyaltyStorage_UpdateOrderAccrual_Call) Return(_a0 error) *MockLoyaltyStorage_UpdateOrderAccrual_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockLoyaltyStorage_UpdateOrderAccrual_Call) RunAndReturn(run func(context.Context, *model.OrderAccrual, time.Time) error) *MockLoyaltyStorage_UpdateOrderAccrual_Call {
	_c.Call.Return(run)
	return _c
}

// NewMockLoyaltyStorage creates a new instance of MockLoyaltyStorage. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockLoyaltyStorage(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockLoyaltyStorage {
	mock := &MockLoyaltyStorage{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
