// Code generated by mockery v2.53.4. DO NOT EDIT.

package mocks

import (
	context "context"

	model "github.com/andrewsvn/gophermart-ls/internal/model"
	mock "github.com/stretchr/testify/mock"

	uuid "github.com/google/uuid"
)

// MockUserStorage is an autogenerated mock type for the UserStorage type
type MockUserStorage struct {
	mock.Mock
}

type MockUserStorage_Expecter struct {
	mock *mock.Mock
}

func (_m *MockUserStorage) EXPECT() *MockUserStorage_Expecter {
	return &MockUserStorage_Expecter{mock: &_m.Mock}
}

// CheckUserExistsByLogin provides a mock function with given fields: ctx, login
func (_m *MockUserStorage) CheckUserExistsByLogin(ctx context.Context, login string) (bool, error) {
	ret := _m.Called(ctx, login)

	if len(ret) == 0 {
		panic("no return value specified for CheckUserExistsByLogin")
	}

	var r0 bool
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string) (bool, error)); ok {
		return rf(ctx, login)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string) bool); ok {
		r0 = rf(ctx, login)
	} else {
		r0 = ret.Get(0).(bool)
	}

	if rf, ok := ret.Get(1).(func(context.Context, string) error); ok {
		r1 = rf(ctx, login)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockUserStorage_CheckUserExistsByLogin_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'CheckUserExistsByLogin'
type MockUserStorage_CheckUserExistsByLogin_Call struct {
	*mock.Call
}

// CheckUserExistsByLogin is a helper method to define mock.On call
//   - ctx context.Context
//   - login string
func (_e *MockUserStorage_Expecter) CheckUserExistsByLogin(ctx interface{}, login interface{}) *MockUserStorage_CheckUserExistsByLogin_Call {
	return &MockUserStorage_CheckUserExistsByLogin_Call{Call: _e.mock.On("CheckUserExistsByLogin", ctx, login)}
}

func (_c *MockUserStorage_CheckUserExistsByLogin_Call) Run(run func(ctx context.Context, login string)) *MockUserStorage_CheckUserExistsByLogin_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string))
	})
	return _c
}

func (_c *MockUserStorage_CheckUserExistsByLogin_Call) Return(_a0 bool, _a1 error) *MockUserStorage_CheckUserExistsByLogin_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockUserStorage_CheckUserExistsByLogin_Call) RunAndReturn(run func(context.Context, string) (bool, error)) *MockUserStorage_CheckUserExistsByLogin_Call {
	_c.Call.Return(run)
	return _c
}

// CreateUser provides a mock function with given fields: ctx, login, authHash
func (_m *MockUserStorage) CreateUser(ctx context.Context, login string, authHash string) (*uuid.UUID, error) {
	ret := _m.Called(ctx, login, authHash)

	if len(ret) == 0 {
		panic("no return value specified for CreateUser")
	}

	var r0 *uuid.UUID
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string, string) (*uuid.UUID, error)); ok {
		return rf(ctx, login, authHash)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string, string) *uuid.UUID); ok {
		r0 = rf(ctx, login, authHash)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*uuid.UUID)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, string, string) error); ok {
		r1 = rf(ctx, login, authHash)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockUserStorage_CreateUser_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'CreateUser'
type MockUserStorage_CreateUser_Call struct {
	*mock.Call
}

// CreateUser is a helper method to define mock.On call
//   - ctx context.Context
//   - login string
//   - authHash string
func (_e *MockUserStorage_Expecter) CreateUser(ctx interface{}, login interface{}, authHash interface{}) *MockUserStorage_CreateUser_Call {
	return &MockUserStorage_CreateUser_Call{Call: _e.mock.On("CreateUser", ctx, login, authHash)}
}

func (_c *MockUserStorage_CreateUser_Call) Run(run func(ctx context.Context, login string, authHash string)) *MockUserStorage_CreateUser_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string), args[2].(string))
	})
	return _c
}

func (_c *MockUserStorage_CreateUser_Call) Return(_a0 *uuid.UUID, _a1 error) *MockUserStorage_CreateUser_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockUserStorage_CreateUser_Call) RunAndReturn(run func(context.Context, string, string) (*uuid.UUID, error)) *MockUserStorage_CreateUser_Call {
	_c.Call.Return(run)
	return _c
}

// GetUserByID provides a mock function with given fields: ctx, id
func (_m *MockUserStorage) GetUserByID(ctx context.Context, id uuid.UUID) (*model.User, error) {
	ret := _m.Called(ctx, id)

	if len(ret) == 0 {
		panic("no return value specified for GetUserByID")
	}

	var r0 *model.User
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, uuid.UUID) (*model.User, error)); ok {
		return rf(ctx, id)
	}
	if rf, ok := ret.Get(0).(func(context.Context, uuid.UUID) *model.User); ok {
		r0 = rf(ctx, id)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*model.User)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, uuid.UUID) error); ok {
		r1 = rf(ctx, id)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockUserStorage_GetUserByID_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetUserByID'
type MockUserStorage_GetUserByID_Call struct {
	*mock.Call
}

// GetUserByID is a helper method to define mock.On call
//   - ctx context.Context
//   - id uuid.UUID
func (_e *MockUserStorage_Expecter) GetUserByID(ctx interface{}, id interface{}) *MockUserStorage_GetUserByID_Call {
	return &MockUserStorage_GetUserByID_Call{Call: _e.mock.On("GetUserByID", ctx, id)}
}

func (_c *MockUserStorage_GetUserByID_Call) Run(run func(ctx context.Context, id uuid.UUID)) *MockUserStorage_GetUserByID_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(uuid.UUID))
	})
	return _c
}

func (_c *MockUserStorage_GetUserByID_Call) Return(_a0 *model.User, _a1 error) *MockUserStorage_GetUserByID_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockUserStorage_GetUserByID_Call) RunAndReturn(run func(context.Context, uuid.UUID) (*model.User, error)) *MockUserStorage_GetUserByID_Call {
	_c.Call.Return(run)
	return _c
}

// GetUserByLogin provides a mock function with given fields: ctx, login
func (_m *MockUserStorage) GetUserByLogin(ctx context.Context, login string) (*model.User, error) {
	ret := _m.Called(ctx, login)

	if len(ret) == 0 {
		panic("no return value specified for GetUserByLogin")
	}

	var r0 *model.User
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string) (*model.User, error)); ok {
		return rf(ctx, login)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string) *model.User); ok {
		r0 = rf(ctx, login)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*model.User)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, string) error); ok {
		r1 = rf(ctx, login)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockUserStorage_GetUserByLogin_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetUserByLogin'
type MockUserStorage_GetUserByLogin_Call struct {
	*mock.Call
}

// GetUserByLogin is a helper method to define mock.On call
//   - ctx context.Context
//   - login string
func (_e *MockUserStorage_Expecter) GetUserByLogin(ctx interface{}, login interface{}) *MockUserStorage_GetUserByLogin_Call {
	return &MockUserStorage_GetUserByLogin_Call{Call: _e.mock.On("GetUserByLogin", ctx, login)}
}

func (_c *MockUserStorage_GetUserByLogin_Call) Run(run func(ctx context.Context, login string)) *MockUserStorage_GetUserByLogin_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string))
	})
	return _c
}

func (_c *MockUserStorage_GetUserByLogin_Call) Return(_a0 *model.User, _a1 error) *MockUserStorage_GetUserByLogin_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockUserStorage_GetUserByLogin_Call) RunAndReturn(run func(context.Context, string) (*model.User, error)) *MockUserStorage_GetUserByLogin_Call {
	_c.Call.Return(run)
	return _c
}

// UpdateUserLoginTS provides a mock function with given fields: ctx, userID
func (_m *MockUserStorage) UpdateUserLoginTS(ctx context.Context, userID uuid.UUID) (bool, error) {
	ret := _m.Called(ctx, userID)

	if len(ret) == 0 {
		panic("no return value specified for UpdateUserLoginTS")
	}

	var r0 bool
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, uuid.UUID) (bool, error)); ok {
		return rf(ctx, userID)
	}
	if rf, ok := ret.Get(0).(func(context.Context, uuid.UUID) bool); ok {
		r0 = rf(ctx, userID)
	} else {
		r0 = ret.Get(0).(bool)
	}

	if rf, ok := ret.Get(1).(func(context.Context, uuid.UUID) error); ok {
		r1 = rf(ctx, userID)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockUserStorage_UpdateUserLoginTS_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'UpdateUserLoginTS'
type MockUserStorage_UpdateUserLoginTS_Call struct {
	*mock.Call
}

// UpdateUserLoginTS is a helper method to define mock.On call
//   - ctx context.Context
//   - userID uuid.UUID
func (_e *MockUserStorage_Expecter) UpdateUserLoginTS(ctx interface{}, userID interface{}) *MockUserStorage_UpdateUserLoginTS_Call {
	return &MockUserStorage_UpdateUserLoginTS_Call{Call: _e.mock.On("UpdateUserLoginTS", ctx, userID)}
}

func (_c *MockUserStorage_UpdateUserLoginTS_Call) Run(run func(ctx context.Context, userID uuid.UUID)) *MockUserStorage_UpdateUserLoginTS_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(uuid.UUID))
	})
	return _c
}

func (_c *MockUserStorage_UpdateUserLoginTS_Call) Return(_a0 bool, _a1 error) *MockUserStorage_UpdateUserLoginTS_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockUserStorage_UpdateUserLoginTS_Call) RunAndReturn(run func(context.Context, uuid.UUID) (bool, error)) *MockUserStorage_UpdateUserLoginTS_Call {
	_c.Call.Return(run)
	return _c
}

// NewMockUserStorage creates a new instance of MockUserStorage. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockUserStorage(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockUserStorage {
	mock := &MockUserStorage{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
