CREATE TABLE IF NOT EXISTS LS_USERS
(
    ID            VARCHAR(36) PRIMARY KEY,
    LOGIN         TEXT UNIQUE NOT NULL,
    AUTH_HASH     TEXT NOT NULL,
    CREATE_TS     TIMESTAMPTZ DEFAULT NOW(),
    LAST_LOGIN_TS TIMESTAMPTZ
);

CREATE TABLE IF NOT EXISTS LS_ORDERS
(
    ID             TEXT PRIMARY KEY,
    USER_ID        TEXT NOT NULL,
    STATUS         TEXT NOT NULL,
    ACCRUAL        NUMERIC(15, 2),
    CREATE_TS      TIMESTAMPTZ DEFAULT NOW(),
    LAST_UPDATE_TS TIMESTAMPTZ DEFAULT NOW()
);

CREATE TABLE IF NOT EXISTS LS_WITHDRAWALS
(
    ID          TEXT PRIMARY KEY,
    USER_ID     TEXT           NOT NULL,
    AMOUNT      NUMERIC(15, 2) NOT NULL,
    CREATE_TS   TIMESTAMPTZ DEFAULT NOW()
);

CREATE INDEX IF NOT EXISTS LS_ORDERS_IX_USER ON LS_ORDERS(USER_ID);

CREATE INDEX IF NOT EXISTS LS_WITHDRAWAL_IX_USER ON LS_WITHDRAWALS(USER_ID);